wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.16.1
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1739056334.593652
    t:
      1:
      - 1
      - 55
      - 105
      2:
      - 1
      - 11
      - 49
      - 55
      - 105
      3:
      - 23
      4: 3.10.9
      5: 0.16.1
      8:
      - 5
      13: darwin-arm64
